import {
  type GeneratedFile,
  type WorkspaceInitParams,
} from "../types.js";
import { DASHBOARD_KPI_DEFINITIONS } from "../data/dashboard-profiles.js";

function buildDashboardOpsReadme(): string {
  return `# Dashboard Operations

Use the generated \`dashboard-ops.mjs\` script to keep the AI harness dashboard current, governed, and portable.

## Commands

- \`node docs/ai-harness/dashboard/scripts/dashboard-ops.mjs refresh\`
  Refresh dashboard-derived fields, synchronize git status, update artifact coverage, align governed sessions, and validate the state before saving.
- \`node docs/ai-harness/dashboard/scripts/dashboard-ops.mjs refresh --patch path/to/patch.json\`
  Apply a JSON patch, then re-run automatic synchronization and strict validation.
- \`node docs/ai-harness/dashboard/scripts/dashboard-ops.mjs validate\`
  Validate the live dashboard state against the stricter shape rules and required KPI profile.
- \`node docs/ai-harness/dashboard/scripts/dashboard-ops.mjs serve --port 43110\`
  Preview the dashboard on a local port.
- \`node docs/ai-harness/dashboard/scripts/dashboard-ops.mjs export-static --out docs/ai-harness/dashboard/exports/latest\`
  Export a portable static dashboard folder and a standalone \`snapshot.html\` file.

## Governed Sessions

- Every meaningful AI session should remain visible in both \`sessionLog\` and \`governedSessions\`.
- The refresh command keeps governed session metadata aligned with git state, verification state, and the current governance stage.
- Domain-required KPI items are re-applied automatically so AX/DX and DevOps views stay intact for both legacy and greenfield projects.

## Legacy Project Adoption

For existing legacy projects:

1. Generate the harness with this MCP.
2. Fill the dashboard state with the first approved modernization goal.
3. Run \`refresh\` after each meaningful chunk so git visibility, session governance, artifacts, and KPIs stay synchronized.
4. Use \`export-static\` whenever stakeholders need a portable snapshot outside the local environment.

## New Project Delivery

For new projects:

1. Keep the dashboard updated from the first planning cycle.
2. Track governed sessions from goal framing through verification and closeout.
3. Track release or draft progress in \`versionLedger\`.
4. Refresh the state before and after implementation, verification, and governance closure.
`;
}

function buildDashboardOpsScript(): string {
  const embeddedDefinitions = JSON.stringify(DASHBOARD_KPI_DEFINITIONS, null, 2);

  return [
    "#!/usr/bin/env node",
    "",
    'import fs from "node:fs";',
    'import path from "node:path";',
    'import http from "node:http";',
    'import { execFileSync } from "node:child_process";',
    'import { fileURLToPath } from "node:url";',
    "",
    "const DASHBOARD_KPI_DEFINITIONS = " + embeddedDefinitions + ";",
    'const GOVERNANCE_STAGE_ORDER = ["governance-open", "plan-1", "review-1", "plan-2", "review-2", "plan-3", "review-3", "goal-freeze", "governance-refresh", "implementation", "verification", "governance-close"];',
    "",
    "const __filename = fileURLToPath(import.meta.url);",
    "const __dirname = path.dirname(__filename);",
    'const dashboardDir = path.resolve(__dirname, "..");',
    'const defaultWorkspaceRoot = path.resolve(__dirname, "../../../..");',
    'const defaultStatePath = path.join(dashboardDir, "state", "dashboard-state.json");',
    'const defaultSchemaPath = path.join(dashboardDir, "state", "dashboard-state.schema.json");',
    "",
    "const args = process.argv.slice(2);",
    'const command = args[0] || "help";',
    "",
    "function getOption(name, fallback) {",
    "  const index = args.indexOf(name);",
    "  if (index === -1 || index === args.length - 1) {",
    "    return fallback;",
    "  }",
    "  return args[index + 1];",
    "}",
    "",
    "function readJsonFile(fullPath) {",
    '  return JSON.parse(fs.readFileSync(fullPath, "utf-8"));',
    "}",
    "",
    "function writeJsonFile(fullPath, value) {",
    "  fs.mkdirSync(path.dirname(fullPath), { recursive: true });",
    '  fs.writeFileSync(fullPath, JSON.stringify(value, null, 2) + "\\n", "utf-8");',
    "}",
    "",
    "function isPlainObject(value) {",
    '  return typeof value === "object" && value !== null && !Array.isArray(value);',
    "}",
    "",
    "function clone(value) {",
    "  return JSON.parse(JSON.stringify(value));",
    "}",
    "",
    "function deepMerge(base, patch) {",
    "  if (Array.isArray(patch)) {",
    "    return clone(patch);",
    "  }",
    "",
    "  if (!isPlainObject(base) || !isPlainObject(patch)) {",
    "    return patch;",
    "  }",
    "",
    "  const result = { ...base };",
    "  for (const [key, value] of Object.entries(patch)) {",
    "    if (Array.isArray(value)) {",
    "      result[key] = clone(value);",
    "      continue;",
    "    }",
    "",
    "    if (isPlainObject(value) && isPlainObject(result[key])) {",
    "      result[key] = deepMerge(result[key], value);",
    "      continue;",
    "    }",
    "",
    "    result[key] = value;",
    "  }",
    "",
    "  return result;",
    "}",
    "",
    "function isString(value) {",
    '  return typeof value === "string";',
    "}",
    "",
    "function isBoolean(value) {",
    '  return typeof value === "boolean";',
    "}",
    "",
    "function isFiniteNumber(value) {",
    '  return typeof value === "number" && Number.isFinite(value);',
    "}",
    "",
    "function typeName(value) {",
    '  if (value === null) return "null";',
    '  if (Array.isArray(value)) return "array";',
    '  return typeof value;',
    "}",
    "",
    "function pushTypeError(errors, fieldPath, expected, actual) {",
    '  errors.push(`${fieldPath} must be ${expected}; received ${typeName(actual)}`);',
    "}",
    "",
    "function requireObject(errors, fieldPath, value) {",
    "  if (!isPlainObject(value)) {",
    '    pushTypeError(errors, fieldPath, "an object", value);',
    "    return null;",
    "  }",
    "  return value;",
    "}",
    "",
    "function requireArray(errors, fieldPath, value) {",
    "  if (!Array.isArray(value)) {",
    '    pushTypeError(errors, fieldPath, "an array", value);',
    "    return null;",
    "  }",
    "  return value;",
    "}",
    "",
    "function requireStringField(errors, objectPath, objectValue, fieldName) {",
    "  if (!isString(objectValue[fieldName])) {",
    '    pushTypeError(errors, `${objectPath}.${fieldName}`, "a string", objectValue[fieldName]);',
    "  }",
    "}",
    "",
    "function requireBooleanField(errors, objectPath, objectValue, fieldName) {",
    "  if (!isBoolean(objectValue[fieldName])) {",
    '    pushTypeError(errors, `${objectPath}.${fieldName}`, "a boolean", objectValue[fieldName]);',
    "  }",
    "}",
    "",
    "function requireNumberField(errors, objectPath, objectValue, fieldName) {",
    "  if (!isFiniteNumber(objectValue[fieldName])) {",
    '    pushTypeError(errors, `${objectPath}.${fieldName}`, "a finite number", objectValue[fieldName]);',
    "  }",
    "}",
    "",
    "function requireStringArrayField(errors, objectPath, objectValue, fieldName) {",
    "  const value = objectValue[fieldName];",
    "  if (!Array.isArray(value) || value.some((entry) => !isString(entry))) {",
    '    pushTypeError(errors, `${objectPath}.${fieldName}`, "an array of strings", value);',
    "  }",
    "}",
    "",
    "function validateObjectArray(errors, fieldPath, value, requiredFields) {",
    "  const items = requireArray(errors, fieldPath, value);",
    "  if (items == null) {",
    "    return null;",
    "  }",
    "",
    "  for (const [index, item] of items.entries()) {",
    "    const entryPath = `${fieldPath}[${index}]`;",
    "    const entry = requireObject(errors, entryPath, item);",
    "    if (entry == null) {",
    "      continue;",
    "    }",
    "",
    "    for (const field of requiredFields.strings || []) {",
    "      requireStringField(errors, entryPath, entry, field);",
    "    }",
    "    for (const field of requiredFields.booleans || []) {",
    "      requireBooleanField(errors, entryPath, entry, field);",
    "    }",
    "    for (const field of requiredFields.numbers || []) {",
    "      requireNumberField(errors, entryPath, entry, field);",
    "    }",
    "    for (const field of requiredFields.stringArrays || []) {",
    "      requireStringArrayField(errors, entryPath, entry, field);",
    "    }",
    "    if (typeof requiredFields.extra === \"function\") {",
    "      requiredFields.extra(errors, entryPath, entry);",
    "    }",
    "  }",
    "",
    "  return items;",
    "}",
    "",
    "function inferDashboardDomainMode(projectType) {",
    "  switch (projectType) {",
    '    case "creative":',
    '      return "creative-narrative";',
    '    case "learning":',
    '      return "knowledge-work";',
    '    case "other":',
    '      return "generic-governance";',
    "    default:",
    '      return "software-delivery";',
    "  }",
    "}",
    "",
    "function filterByProjectType(definition, projectType) {",
    "  return (",
    "    definition.relevantProjectTypes == null ||",
    "    (projectType != null && definition.relevantProjectTypes.includes(projectType))",
    "  );",
    "}",
    "",
    "function getRequiredDashboardKpis(projectType) {",
    "  const domainMode = inferDashboardDomainMode(projectType);",
    "  return DASHBOARD_KPI_DEFINITIONS.filter(",
    "    (definition) =>",
    "      definition.appliesToModes.includes(domainMode) &&",
    "      filterByProjectType(definition, projectType)",
    "  );",
    "}",
    "",
    "function getDashboardKpiProfile(projectType) {",
    "  const definitions = getRequiredDashboardKpis(projectType);",
    "  const domainMode = inferDashboardDomainMode(projectType);",
    "",
    "  switch (domainMode) {",
    '    case "creative-narrative":',
    "      return {",
    '        id: "creative-governed-kpis",',
    '        label: "Creative Governance KPI Profile",',
    "        requiredKpiIds: definitions.map((definition) => definition.id),",
    '        perspectives: ["AX/DX", "Creative Operations"],',
    "        rationale: [",
    '          "Narrative continuity, character state, and editorial progress must remain visible across sessions.",',
    '          "Stakeholders should be able to assess story momentum without reading manuscript diffs or chat transcripts.",',
    "        ],",
    "      };",
    '    case "knowledge-work":',
    "      return {",
    '        id: "knowledge-governed-kpis",',
    '        label: "Knowledge Work KPI Profile",',
    "        requiredKpiIds: definitions.map((definition) => definition.id),",
    '        perspectives: ["AX/DX", "Research Operations"],',
    "        rationale: [",
    '          "Learning and research work must keep evidence quality and iteration closure visible.",',
    '          "A reviewer should be able to understand the current module state, sources, and next step immediately.",',
    "        ],",
    "      };",
    '    case "generic-governance":',
    "      return {",
    '        id: "general-governed-kpis",',
    '        label: "General Governance KPI Profile",',
    "        requiredKpiIds: definitions.map((definition) => definition.id),",
    '        perspectives: ["AX/DX", "Operations"],',
    "        rationale: [",
    '          "Transformation initiatives need milestone, owner, and decision traceability even outside software delivery.",',
    '          "The dashboard should remain readable by broad stakeholder groups.",',
    "        ],",
    "      };",
    "    default:",
    "      return {",
    '        id: "software-devops-governed-kpis",',
    '        label: "Software Delivery / DevOps KPI Profile",',
    "        requiredKpiIds: definitions.map((definition) => definition.id),",
    '        perspectives: ["AX/DX", "DevOps", "Engineering"],',
    "        rationale: [",
    '          "Software delivery requires governance visibility plus DevOps-grade release and operability traceability.",',
    '          "Every meaningful session should connect planning, implementation, testing, git history, and release evidence.",',
    "        ],",
    "      };",
    "  }",
    "}",
    "",
    "function validateDashboardStateShape(value) {",
    "  const errors = [];",
    '  const root = requireObject(errors, "dashboardState", value);',
    "  if (root == null) {",
    "    return { valid: false, errors };",
    "  }",
    "",
    "  const requiredTopLevelKeys = [",
    '    "meta",',
    '    "workspace",',
    '    "executiveSummary",',
    '    "progressState",',
    '    "governanceState",',
    '    "kpiProfile",',
    '    "kpis",',
    '    "errors",',
    '    "gitStatus",',
    '    "sessionLog",',
    '    "governedSessions",',
    '    "artifacts",',
    '    "domainLens",',
    '    "timeline",',
    '    "entities",',
    '    "versionLedger",',
    "  ];",
    "",
    "  for (const key of requiredTopLevelKeys) {",
    "    if (!(key in root)) {",
    '      errors.push(`dashboardState.${key} is required`);',
    "    }",
    "  }",
    "",
    '  const meta = requireObject(errors, "dashboardState.meta", root.meta);',
    "  if (meta != null) {",
    '    requireStringField(errors, "dashboardState.meta", meta, "schemaVersion");',
    '    requireStringField(errors, "dashboardState.meta", meta, "generatedBy");',
    '    requireStringField(errors, "dashboardState.meta", meta, "dashboardDesignSystem");',
    '    requireStringField(errors, "dashboardState.meta", meta, "refreshRule");',
    "  }",
    "",
    '  const workspace = requireObject(errors, "dashboardState.workspace", root.workspace);',
    "  if (workspace != null) {",
    '    requireStringField(errors, "dashboardState.workspace", workspace, "name");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "purpose");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "projectType");',
    '    requireStringArrayField(errors, "dashboardState.workspace", workspace, "primaryDomains");',
    '    requireStringArrayField(errors, "dashboardState.workspace", workspace, "techStack");',
    '    requireStringArrayField(errors, "dashboardState.workspace", workspace, "targetIDEs");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "harnessProfile");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "governanceProfile");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "autonomyMode");',
    '    requireStringField(errors, "dashboardState.workspace", workspace, "tokenBudget");',
    "  }",
    "",
    '  const executiveSummary = requireObject(errors, "dashboardState.executiveSummary", root.executiveSummary);',
    "  if (executiveSummary != null) {",
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "headline");',
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "overallStatus");',
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "currentStage");',
    '    requireNumberField(errors, "dashboardState.executiveSummary", executiveSummary, "overallProgressPercent");',
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "nextDecision");',
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "lastUpdated");',
    '    requireStringField(errors, "dashboardState.executiveSummary", executiveSummary, "audienceNote");',
    "  }",
    "",
    '  const progressState = requireObject(errors, "dashboardState.progressState", root.progressState);',
    "  if (progressState != null) {",
    '    requireStringField(errors, "dashboardState.progressState", progressState, "activeGoal");',
    '    requireStringField(errors, "dashboardState.progressState", progressState, "activeChunk");',
    '    requireStringField(errors, "dashboardState.progressState", progressState, "currentOwner");',
    '    requireBooleanField(errors, "dashboardState.progressState", progressState, "blocked");',
    '    requireStringField(errors, "dashboardState.progressState", progressState, "riskLevel");',
    '    requireStringField(errors, "dashboardState.progressState", progressState, "nextAction");',
    "  }",
    "",
    "  validateObjectArray(errors, \"dashboardState.progressState.stageChecklist\", progressState?.stageChecklist, {",
    '    strings: ["id", "label", "status"],',
    "  });",
    "  validateObjectArray(errors, \"dashboardState.progressState.workstreams\", progressState?.workstreams, {",
    '    strings: ["id", "label", "owner", "status", "note"],',
    '    numbers: ["progressPercent"],',
    "  });",
    "",
    '  const governanceState = requireObject(errors, "dashboardState.governanceState", root.governanceState);',
    "  if (governanceState != null) {",
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "policyId");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "policyLabel");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "status");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "sessionGovernanceRule");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "latestApprovedStage");',
    '    requireBooleanField(errors, "dashboardState.governanceState", governanceState, "goalFrozen");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "dashboardSyncStatus");',
    '    requireStringArrayField(errors, "dashboardState.governanceState", governanceState, "requiredArtifacts");',
    '    requireStringArrayField(errors, "dashboardState.governanceState", governanceState, "requiredKpiIds");',
    '    requireStringArrayField(errors, "dashboardState.governanceState", governanceState, "mandatorySessionFields");',
    '    requireStringField(errors, "dashboardState.governanceState", governanceState, "visibilityRule");',
    "  }",
    "",
    '  const kpiProfile = requireObject(errors, "dashboardState.kpiProfile", root.kpiProfile);',
    "  if (kpiProfile != null) {",
    '    requireStringField(errors, "dashboardState.kpiProfile", kpiProfile, "id");',
    '    requireStringField(errors, "dashboardState.kpiProfile", kpiProfile, "label");',
    '    requireStringArrayField(errors, "dashboardState.kpiProfile", kpiProfile, "requiredKpiIds");',
    '    requireStringArrayField(errors, "dashboardState.kpiProfile", kpiProfile, "perspectives");',
    '    requireStringArrayField(errors, "dashboardState.kpiProfile", kpiProfile, "rationale");',
    "  }",
    "",
    "  const kpis = validateObjectArray(errors, \"dashboardState.kpis\", root.kpis, {",
    '    strings: ["id", "label", "value", "target", "status", "interpretation"],',
    '    booleans: ["required"],',
    '    stringArrays: ["perspectives"],',
    "  });",
    "",
    "  const issues = validateObjectArray(errors, \"dashboardState.errors\", root.errors, {",
    '    strings: ["id", "severity", "status", "summary", "owner", "firstSeenAt", "lastSeenAt"],',
    "  });",
    "",
    '  const gitStatus = requireObject(errors, "dashboardState.gitStatus", root.gitStatus);',
    "  if (gitStatus != null) {",
    '    requireBooleanField(errors, "dashboardState.gitStatus", gitStatus, "repositoryExpected");',
    '    requireStringField(errors, "dashboardState.gitStatus", gitStatus, "trackedByGit");',
    '    requireStringField(errors, "dashboardState.gitStatus", gitStatus, "provider");',
    '    requireStringField(errors, "dashboardState.gitStatus", gitStatus, "defaultBranch");',
    '    requireStringField(errors, "dashboardState.gitStatus", gitStatus, "currentBranch");',
    '    requireStringArrayField(errors, "dashboardState.gitStatus", gitStatus, "auditExpectations");',
    '    const lastCommit = requireObject(errors, "dashboardState.gitStatus.lastCommit", gitStatus.lastCommit);',
    "    if (lastCommit != null) {",
    '      requireStringField(errors, "dashboardState.gitStatus.lastCommit", lastCommit, "sha");',
    '      requireStringField(errors, "dashboardState.gitStatus.lastCommit", lastCommit, "message");',
    '      requireStringField(errors, "dashboardState.gitStatus.lastCommit", lastCommit, "author");',
    '      requireStringField(errors, "dashboardState.gitStatus.lastCommit", lastCommit, "committedAt");',
    "    }",
    '    const workingTree = requireObject(errors, "dashboardState.gitStatus.workingTree", gitStatus.workingTree);',
    "    if (workingTree != null) {",
    '      requireStringField(errors, "dashboardState.gitStatus.workingTree", workingTree, "status");',
    '      requireStringField(errors, "dashboardState.gitStatus.workingTree", workingTree, "stagedChanges");',
    '      requireStringField(errors, "dashboardState.gitStatus.workingTree", workingTree, "unstagedChanges");',
    '      requireStringField(errors, "dashboardState.gitStatus.workingTree", workingTree, "untrackedFiles");',
    "    }",
    "  }",
    "",
    "  const sessionLog = validateObjectArray(errors, \"dashboardState.sessionLog\", root.sessionLog, {",
    '    strings: ["id", "title", "status", "stage", "startedAt", "endedAt", "owner", "note"],',
    '    stringArrays: ["outputs"],',
    "  });",
    "",
    "  const governedSessions = validateObjectArray(errors, \"dashboardState.governedSessions\", root.governedSessions, {",
    '    strings: ["id", "title", "status", "owner", "agentRole", "governanceStatus", "goal", "chunkId", "startedAt", "endedAt", "nextStep"],',
    '    stringArrays: ["outputs"],',
    "    extra(errors, entryPath, session) {",
    '      const governance = requireObject(errors, `${entryPath}.governance`, session.governance);',
    "      if (governance != null) {",
    '        requireBooleanField(errors, `${entryPath}.governance`, governance, "opened");',
    '        requireNumberField(errors, `${entryPath}.governance`, governance, "latestPlanRound");',
    '        requireNumberField(errors, `${entryPath}.governance`, governance, "latestReviewRound");',
    '        requireBooleanField(errors, `${entryPath}.governance`, governance, "goalFrozen");',
    '        requireBooleanField(errors, `${entryPath}.governance`, governance, "closeoutReady");',
    '        requireStringField(errors, `${entryPath}.governance`, governance, "evidenceFreshness");',
    "      }",
    '      const verification = requireObject(errors, `${entryPath}.verification`, session.verification);',
    "      if (verification != null) {",
    '        requireStringField(errors, `${entryPath}.verification`, verification, "testsStatus");',
    '        requireStringField(errors, `${entryPath}.verification`, verification, "reviewStatus");',
    '        requireStringField(errors, `${entryPath}.verification`, verification, "remediationStatus");',
    "      }",
    '      const git = requireObject(errors, `${entryPath}.git`, session.git);',
    "      if (git != null) {",
    '        requireStringField(errors, `${entryPath}.git`, git, "branch");',
    '        requireStringField(errors, `${entryPath}.git`, git, "commit");',
    "      }",
    "    },",
    "  });",
    "",
    "  validateObjectArray(errors, \"dashboardState.artifacts\", root.artifacts, {",
    '    strings: ["id", "label", "path", "status", "owner"],',
    "  });",
    "  validateObjectArray(errors, \"dashboardState.timeline\", root.timeline, {",
    '    strings: ["id", "label", "type", "status", "owner", "note"],',
    "  });",
    "  validateObjectArray(errors, \"dashboardState.entities\", root.entities, {",
    '    strings: ["id", "label", "type", "status", "summary"],',
    "  });",
    "  validateObjectArray(errors, \"dashboardState.versionLedger\", root.versionLedger, {",
    '    strings: ["id", "label", "status", "scope"],',
    '    numbers: ["progressPercent"],',
    "  });",
    "",
    '  const domainLens = requireObject(errors, "dashboardState.domainLens", root.domainLens);',
    "  if (domainLens != null) {",
    '    requireStringField(errors, "dashboardState.domainLens", domainLens, "mode");',
    '    requireStringField(errors, "dashboardState.domainLens", domainLens, "title");',
    '    requireStringField(errors, "dashboardState.domainLens", domainLens, "primaryQuestion");',
    "  }",
    "",
    "  if (workspace != null && kpiProfile != null && kpis != null) {",
    "    const expectedProfile = getDashboardKpiProfile(workspace.projectType);",
    "    const actualKpiIds = new Set(kpis.filter((item) => isPlainObject(item)).map((item) => String(item.id)));",
    "    if (kpiProfile.id !== expectedProfile.id) {",
    '      errors.push(`dashboardState.kpiProfile.id must be "${expectedProfile.id}" for projectType "${String(workspace.projectType || "other")}"`);',
    "    }",
    "    for (const requiredKpiId of expectedProfile.requiredKpiIds) {",
    "      if (!actualKpiIds.has(requiredKpiId)) {",
    '        errors.push(`dashboardState.kpis is missing required KPI "${requiredKpiId}" for profile "${expectedProfile.id}"`);',
    "      }",
    "    }",
    "",
    "    if (governanceState != null) {",
    "      const governanceRequiredKpis = Array.isArray(governanceState.requiredKpiIds)",
    "        ? new Set(governanceState.requiredKpiIds.map((item) => String(item)))",
    "        : new Set();",
    "      for (const requiredKpiId of expectedProfile.requiredKpiIds) {",
    "        if (!governanceRequiredKpis.has(requiredKpiId)) {",
    '          errors.push(`dashboardState.governanceState.requiredKpiIds is missing required KPI "${requiredKpiId}"`);',
    "        }",
    "      }",
    "    }",
    "  }",
    "",
    "  if (sessionLog != null && governedSessions != null) {",
    "    const governedSessionIds = new Set(",
    "      governedSessions",
    "        .filter((item) => isPlainObject(item))",
    "        .map((item) => String(item.id))",
    "    );",
    "    for (const session of sessionLog) {",
    "      if (isPlainObject(session) && isString(session.id) && !governedSessionIds.has(session.id)) {",
    '        errors.push(`dashboardState.governedSessions is missing a governed entry for session "${session.id}"`);',
    "      }",
    "    }",
    "  }",
    "",
    "  if (issues != null && issues.some((issue) => isPlainObject(issue) && ![\"open\", \"closed\", \"monitoring\"].includes(String(issue.status || \"\")))) {",
    '    errors.push("dashboardState.errors entries should use open, closed, or monitoring statuses");',
    "  }",
    "",
    "  return { valid: errors.length === 0, errors };",
    "}",
    "",
    "function safeRelativePath(rootDir, targetPath) {",
    '  return path.relative(rootDir, targetPath).replace(/\\\\/g, "/");',
    "}",
    "",
    "function getWorkspaceRoot() {",
    '  return path.resolve(getOption("--workspace-root", defaultWorkspaceRoot));',
    "}",
    "",
    "function getStatePath() {",
    '  return path.resolve(getOption("--state", defaultStatePath));',
    "}",
    "",
    "function getGitFixturePath() {",
    '  const fromArgs = getOption("--git-fixture", "");',
    "  if (fromArgs) {",
    "    return path.resolve(fromArgs);",
    "  }",
    "  if (process.env.DASHBOARD_GIT_FIXTURE) {",
    "    return path.resolve(process.env.DASHBOARD_GIT_FIXTURE);",
    "  }",
    '  return "";',
    "}",
    "",
    "function listFilesRecursively(fullPath) {",
    "  if (!fs.existsSync(fullPath)) {",
    "    return [];",
    "  }",
    "  const stat = fs.statSync(fullPath);",
    "  if (stat.isFile()) {",
    "    return [fullPath];",
    "  }",
    "  const files = [];",
    "  for (const entry of fs.readdirSync(fullPath, { withFileTypes: true })) {",
    "    const entryPath = path.join(fullPath, entry.name);",
    "    if (entry.isDirectory()) {",
    "      files.push(...listFilesRecursively(entryPath));",
    "      continue;",
    "    }",
    "    if (entry.isFile()) {",
    "      files.push(entryPath);",
    "    }",
    "  }",
    "  return files;",
    "}",
    "",
    "function latestMtime(pathsToCheck) {",
    "  let latest = 0;",
    "  for (const fullPath of pathsToCheck) {",
    "    for (const filePath of listFilesRecursively(fullPath)) {",
    "      try {",
    "        latest = Math.max(latest, fs.statSync(filePath).mtimeMs);",
    "      } catch {",
    "        // ignore inaccessible files",
    "      }",
    "    }",
    "  }",
    "  return latest;",
    "}",
    "",
    "function stageProgressPercent(stageChecklist) {",
    "  if (!Array.isArray(stageChecklist) || stageChecklist.length === 0) {",
    "    return 0;",
    "  }",
    "",
    "  const statusWeight = (status) => {",
    '    const normalized = String(status || "").toLowerCase();',
    '    if (["complete", "completed", "done", "closed"].includes(normalized)) return 100;',
    '    if (["in-progress", "active"].includes(normalized)) return 50;',
    "    return 0;",
    "  };",
    "",
    "  const total = stageChecklist.reduce((sum, item) => sum + statusWeight(item.status), 0);",
    "  return Math.round(total / stageChecklist.length);",
    "}",
    "",
    "function deriveCurrentStage(stageChecklist) {",
    "  if (!Array.isArray(stageChecklist) || stageChecklist.length === 0) {",
    '    return "unknown";',
    "  }",
    "  const active = stageChecklist.find((item) => [\"in-progress\", \"active\"].includes(String(item.status || \"\").toLowerCase()));",
    "  if (active) {",
    '    return active.id || active.label || "in-progress";',
    "  }",
    "  const nextTodo = stageChecklist.find((item) => [\"todo\", \"planned\", \"not-started\", \"draft\"].includes(String(item.status || \"\").toLowerCase()));",
    "  if (nextTodo) {",
    '    return nextTodo.id || nextTodo.label || "planned";',
    "  }",
    "  const last = stageChecklist.at(-1);",
    '  return (last && (last.id || last.label)) || "complete";',
    "}",
    "",
    "function isStageComplete(stageChecklist, stageId) {",
    "  const match = Array.isArray(stageChecklist) ? stageChecklist.find((item) => item.id === stageId) : null;",
    '  return ["complete", "completed", "done", "closed"].includes(String(match?.status || "").toLowerCase());',
    "}",
    "",
    "function countCompletedStages(stageChecklist, prefix) {",
    "  if (!Array.isArray(stageChecklist)) {",
    "    return 0;",
    "  }",
    "  return stageChecklist.filter(",
    "    (item) => String(item.id || \"\").startsWith(prefix) && isStageComplete(stageChecklist, item.id)",
    "  ).length;",
    "}",
    "",
    "function findLatestApprovedStage(stageChecklist) {",
    "  if (!Array.isArray(stageChecklist) || stageChecklist.length === 0) {",
    '    return "governance-open";',
    "  }",
    "",
    '  let latest = "governance-open";',
    "  for (const stageId of GOVERNANCE_STAGE_ORDER) {",
    "    if (isStageComplete(stageChecklist, stageId)) {",
    "      latest = stageId;",
    "      continue;",
    "    }",
    "    break;",
    "  }",
    "",
    "  return latest;",
    "}",
    "",
    "function runGit(argsToRun, workspaceRoot) {",
    '  return execFileSync("git", argsToRun, {',
    "    cwd: workspaceRoot,",
    '    encoding: "utf-8",',
    '    stdio: ["ignore", "pipe", "pipe"],',
    "  }).trim();",
    "}",
    "",
    "function collectGitStatus(workspaceRoot) {",
    "  const fallback = {",
    "    repositoryExpected: true,",
    '    trackedByGit: "no",',
    '    provider: "git",',
    '    defaultBranch: "main",',
    '    currentBranch: "TBD",',
    "    lastCommit: {",
    '      sha: "TBD",',
    '      message: "TBD",',
    '      author: "TBD",',
    '      committedAt: "TBD",',
    "    },",
    "    workingTree: {",
    '      status: "unknown",',
    '      stagedChanges: "TBD",',
    '      unstagedChanges: "TBD",',
    '      untrackedFiles: "TBD",',
    "    },",
    '    auditExpectations: ["Track dashboard JSON files in version control.", "Track governance documents and handover files in version control.", "Refresh git snapshot after each meaningful session close."],',
    "  };",
    "",
    "  const fixturePath = getGitFixturePath();",
    "  if (fixturePath) {",
    "    try {",
    "      return deepMerge(fallback, readJsonFile(fixturePath));",
    "    } catch {",
    "      return fallback;",
    "    }",
    "  }",
    "",
    "  try {",
    '    const repoRoot = runGit(["rev-parse", "--show-toplevel"], workspaceRoot);',
    '    const currentBranch = runGit(["branch", "--show-current"], workspaceRoot) || "detached-head";',
    '    let defaultBranch = "main";',
    "    try {",
    '      const symbolicHead = runGit(["symbolic-ref", "refs/remotes/origin/HEAD"], workspaceRoot);',
    '      const segments = symbolicHead.split("/");',
    "      defaultBranch = segments.at(-1) || defaultBranch;",
    "    } catch {",
    "      try {",
    '        defaultBranch = runGit(["rev-parse", "--abbrev-ref", "HEAD"], workspaceRoot) || defaultBranch;',
    "      } catch {",
    "        // keep fallback",
    "      }",
    "    }",
    "",
    '    let sha = "TBD";',
    '    let message = "TBD";',
    '    let author = "TBD";',
    '    let committedAt = "TBD";',
    "    try {",
    '      sha = runGit(["rev-parse", "HEAD"], workspaceRoot);',
    '      message = runGit(["log", "-1", "--pretty=%s"], workspaceRoot);',
    '      author = runGit(["log", "-1", "--pretty=%an"], workspaceRoot);',
    '      committedAt = runGit(["log", "-1", "--pretty=%aI"], workspaceRoot);',
    "    } catch {",
    "      // repo without commits yet",
    "    }",
    "",
    '    const statusPorcelain = runGit(["status", "--porcelain"], workspaceRoot);',
    "    const lines = statusPorcelain.length > 0 ? statusPorcelain.split(/\\r?\\n/) : [];",
    "    let stagedChanges = 0;",
    "    let unstagedChanges = 0;",
    "    let untrackedFiles = 0;",
    "",
    "    for (const line of lines) {",
    "      if (!line) continue;",
    "      const indexStatus = line[0];",
    "      const workTreeStatus = line[1];",
    '      if (indexStatus === "?" && workTreeStatus === "?") {',
    "        untrackedFiles += 1;",
    "        continue;",
    "      }",
    '      if (indexStatus && indexStatus !== " ") {',
    "        stagedChanges += 1;",
    "      }",
    '      if (workTreeStatus && workTreeStatus !== " ") {',
    "        unstagedChanges += 1;",
    "      }",
    "    }",
    "",
    "    return {",
    "      repositoryExpected: true,",
    '      trackedByGit: repoRoot ? "yes" : "no",',
    '      provider: "git",',
    "      defaultBranch,",
    "      currentBranch,",
    "      lastCommit: { sha, message, author, committedAt },",
    "      workingTree: {",
    '        status: stagedChanges === 0 && unstagedChanges === 0 && untrackedFiles === 0 ? "clean" : "dirty",',
    "        stagedChanges: String(stagedChanges),",
    "        unstagedChanges: String(unstagedChanges),",
    "        untrackedFiles: String(untrackedFiles),",
    "      },",
    "      auditExpectations: fallback.auditExpectations,",
    "    };",
    "  } catch {",
    "    return fallback;",
    "  }",
    "}",
    "",
    "function buildRequiredArtifactPaths(state) {",
    '  const basePaths = [".github/ai-harness/harness-manifest.yaml", ".github/ai-harness/operating-model.md", "docs/context/", "docs/reviews/", "docs/plans/", "docs/handovers/", "docs/work-logs/", "docs/ai-harness/dashboard/state/dashboard-state.json"];',
    "  const artifactPaths = Array.isArray(state.artifacts)",
    "    ? state.artifacts.map((artifact) => String(artifact.path || \"\")).filter(Boolean)",
    "    : [];",
    "  return [...new Set([...basePaths, ...artifactPaths])];",
    "}",
    "",
    "function refreshArtifactStatuses(state, workspaceRoot) {",
    "  const artifacts = Array.isArray(state.artifacts) ? state.artifacts : [];",
    "  state.artifacts = artifacts.map((artifact) => ({",
    "    ...artifact,",
    "    status: fs.existsSync(path.join(workspaceRoot, artifact.path || \"\")) ? \"present\" : \"missing\",",
    "  }));",
    "}",
    "",
    "function refreshSessionLog(state) {",
    "  const sessionLog = Array.isArray(state.sessionLog) ? [...state.sessionLog] : [];",
    '  const now = new Date().toISOString();',
    '  const currentStage = String(state.executiveSummary?.currentStage || deriveCurrentStage(state.progressState?.stageChecklist || []));',
    "",
    "  if (sessionLog.length === 0) {",
    "    sessionLog.push({",
    '      id: "session-0001",',
    '      title: "Dashboard refresh",',
    '      status: "complete",',
    "      stage: currentStage,",
    "      startedAt: now,",
    "      endedAt: now,",
    '      owner: "dashboard-ops",',
    '      outputs: ["docs/ai-harness/dashboard/state/dashboard-state.json"],',
    '      note: "Dashboard state synchronized from repository, governance, and git signals.",',
    "    });",
    "    state.sessionLog = sessionLog;",
    "    return;",
    "  }",
    "",
    "  const last = sessionLog[sessionLog.length - 1];",
    '  if (last && last.id === "session-auto-refresh") {',
    "    last.endedAt = now;",
    "    last.stage = currentStage;",
    '    last.note = "Dashboard state synchronized from repository, governance, and git signals.";',
    "    state.sessionLog = sessionLog;",
    "    return;",
    "  }",
    "",
    "  sessionLog.push({",
    '    id: "session-auto-refresh",',
    '    title: "Dashboard refresh",',
    '    status: "complete",',
    "    stage: currentStage,",
    "    startedAt: now,",
    "    endedAt: now,",
    '    owner: "dashboard-ops",',
    '    outputs: ["docs/ai-harness/dashboard/state/dashboard-state.json"],',
    '    note: "Dashboard state synchronized from repository, governance, and git signals.",',
    "  });",
    "  state.sessionLog = sessionLog;",
    "}",
    "",
    "function refreshGovernanceState(state) {",
    "  const projectType = state.workspace?.projectType;",
    "  const stageChecklist = Array.isArray(state.progressState?.stageChecklist) ? state.progressState.stageChecklist : [];",
    "  const profile = getDashboardKpiProfile(projectType);",
    '  const latestApprovedStage = findLatestApprovedStage(stageChecklist);',
    '  const goalFrozen = isStageComplete(stageChecklist, "goal-freeze");',
    "  const existing = isPlainObject(state.governanceState) ? state.governanceState : {};",
    "",
    "  state.kpiProfile = profile;",
    "  state.governanceState = {",
    '    policyId: String(existing.policyId || "three-plan-three-review"),',
    '    policyLabel: String(existing.policyLabel || "Three-Plan / Three-Review Governance"),',
    '    status: String(existing.status || (state.progressState?.blocked ? "attention-needed" : "active")),',
    "    sessionGovernanceRule: String(",
    '      existing.sessionGovernanceRule ||',
    '      "Every meaningful AI session must open governance, preserve evidence, and close governance before completion."',
    "    ),",
    "    latestApprovedStage,",
    "    goalFrozen,",
    '    dashboardSyncStatus: "current",',
    "    requiredArtifacts: buildRequiredArtifactPaths(state),",
    "    requiredKpiIds: profile.requiredKpiIds,",
    '    mandatorySessionFields: Array.isArray(existing.mandatorySessionFields) && existing.mandatorySessionFields.length > 0',
    "      ? existing.mandatorySessionFields",
    '      : ["goal", "chunkId", "governance.opened", "governance.latestPlanRound", "governance.latestReviewRound", "verification.reviewStatus", "nextStep"],',
    "    visibilityRule: String(",
    '      existing.visibilityRule ||',
    '      "Every governed session should be visible to operators, product owners, reviewers, and non-developer stakeholders."',
    "    ),",
    "  };",
    "}",
    "",
    "function refreshGovernedSessions(state) {",
    "  const sessionLog = Array.isArray(state.sessionLog) ? state.sessionLog : [];",
    "  const existingGovernedSessions = Array.isArray(state.governedSessions) ? state.governedSessions : [];",
    "  const existingById = new Map(",
    "    existingGovernedSessions",
    "      .filter((session) => isPlainObject(session) && isString(session.id))",
    "      .map((session) => [session.id, session])",
    "  );",
    "",
    '  const now = new Date().toISOString();',
    "  const stageChecklist = Array.isArray(state.progressState?.stageChecklist) ? state.progressState.stageChecklist : [];",
    '  const latestPlanRound = Math.max(1, countCompletedStages(stageChecklist, "plan-"));',
    '  const latestReviewRound = countCompletedStages(stageChecklist, "review-");',
    '  const goalFrozen = Boolean(state.governanceState?.goalFrozen || isStageComplete(stageChecklist, "goal-freeze"));',
    '  const branch = String(state.gitStatus?.currentBranch || "TBD");',
    '  const commit = String(state.gitStatus?.lastCommit?.sha || "TBD");',
    '  const defaultGoal = String(state.progressState?.activeGoal || state.workspace?.purpose || "TBD");',
    '  const defaultChunk = String(state.progressState?.activeChunk || "chunk-unset");',
    '  const nextAction = String(state.progressState?.nextAction || "Refresh governance and define the next verified step.");',
    '  const softwareDelivery = inferDashboardDomainMode(state.workspace?.projectType) === "software-delivery";',
    "",
    "  const governedSessions = sessionLog.map((session, index) => {",
    "    const existing = existingById.get(session.id) || {};",
    "    const outputs = Array.isArray(existing.outputs) && existing.outputs.length > 0",
    "      ? existing.outputs",
    "      : Array.isArray(session.outputs) && session.outputs.length > 0",
    "        ? session.outputs",
    '        : ["docs/ai-harness/dashboard/state/dashboard-state.json"];',
    "",
    "    const verification = {",
    '      testsStatus: String(existing.verification?.testsStatus || (softwareDelivery ? "pending" : "not-applicable")),',
    '      reviewStatus: String(existing.verification?.reviewStatus || "pending"),',
    '      remediationStatus: String(existing.verification?.remediationStatus || "not-started"),',
    "    };",
    "",
    '    const completed = ["complete", "completed", "done", "closed"].includes(String(session.status || "").toLowerCase());',
    "    const governance = {",
    "      opened: Boolean(existing.governance?.opened ?? true),",
    "      latestPlanRound: Number(existing.governance?.latestPlanRound ?? latestPlanRound),",
    "      latestReviewRound: Number(existing.governance?.latestReviewRound ?? latestReviewRound),",
    "      goalFrozen: Boolean(existing.governance?.goalFrozen ?? goalFrozen),",
    "      closeoutReady: Boolean(",
    "        existing.governance?.closeoutReady ??",
    "          (completed && verification.reviewStatus !== \"pending\")",
    "      ),",
    '      evidenceFreshness: String(existing.governance?.evidenceFreshness || (outputs.length > 0 ? "current" : "missing")),',
    "    };",
    "",
    '    let governanceStatus = "active";',
    "    if (!governance.opened || outputs.length === 0) {",
    '      governanceStatus = "attention-needed";',
    "    } else if (completed) {",
    '      governanceStatus = governance.closeoutReady ? "governed" : "review-pending";',
    "    }",
    "",
    "    return {",
    "      id: String(session.id || `session-${String(index + 1).padStart(4, \"0\")}`),",
    '      title: String(session.title || "Governed session"),',
    '      status: String(session.status || "complete"),',
    '      owner: String(session.owner || "dashboard-ops"),',
    '      agentRole: String(existing.agentRole || session.owner || "dashboard-ops"),',
    "      governanceStatus,",
    '      goal: String(existing.goal || defaultGoal),',
    '      chunkId: String(existing.chunkId || defaultChunk),',
    "      startedAt: String(session.startedAt || now),",
    "      endedAt: String(session.endedAt || now),",
    "      governance,",
    "      verification,",
    "      git: {",
    '        branch: String(existing.git?.branch || branch),',
    '        commit: String(existing.git?.commit || commit),',
    "      },",
    "      outputs,",
    '      nextStep: String(existing.nextStep || nextAction),',
    "    };",
    "  });",
    "",
    "  const sessionIds = new Set(governedSessions.map((session) => session.id));",
    "  for (const existing of existingGovernedSessions) {",
    "    if (isPlainObject(existing) && isString(existing.id) && !sessionIds.has(existing.id)) {",
    "      governedSessions.push(existing);",
    "    }",
    "  }",
    "",
    "  if (governedSessions.length === 0) {",
    "    governedSessions.push({",
    '      id: "session-0001",',
    '      title: "Dashboard bootstrap",',
    '      status: "complete",',
    '      owner: "dashboard-ops",',
    '      agentRole: "dashboard-ops",',
    '      governanceStatus: "governed",',
    "      goal: defaultGoal,",
    "      chunkId: defaultChunk,",
    "      startedAt: now,",
    "      endedAt: now,",
    "      governance: {",
    "        opened: true,",
    "        latestPlanRound,",
    "        latestReviewRound,",
    "        goalFrozen,",
    "        closeoutReady: true,",
    '        evidenceFreshness: "current",',
    "      },",
    "      verification: {",
    '        testsStatus: softwareDelivery ? "pending" : "not-applicable",',
    '        reviewStatus: "pending",',
    '        remediationStatus: "not-started",',
    "      },",
    "      git: { branch, commit },",
    '      outputs: ["docs/ai-harness/dashboard/state/dashboard-state.json"],',
    "      nextStep: nextAction,",
    "    });",
    "  }",
    "",
    "  state.governedSessions = governedSessions;",
    "}",
    "",
    "function upsertKpi(kpis, nextKpi) {",
    "  const existingIndex = kpis.findIndex((item) => item.id === nextKpi.id);",
    "  if (existingIndex >= 0) {",
    "    kpis[existingIndex] = { ...kpis[existingIndex], ...nextKpi };",
    "    return;",
    "  }",
    "  kpis.push(nextKpi);",
    "}",
    "",
    "function statusFromFraction(numerator, denominator) {",
    "  if (denominator <= 0) {",
    '    return "warning";',
    "  }",
    "  if (numerator >= denominator) {",
    '    return "ok";',
    "  }",
    "  if (numerator > 0) {",
    '    return "warning";',
    "  }",
    '  return "risk";',
    "}",
    "",
    "function refreshGovernanceKpis(state, workspaceRoot) {",
    "  const projectType = state.workspace?.projectType;",
    "  const requiredDefinitions = getRequiredDashboardKpis(projectType);",
    "  const profile = getDashboardKpiProfile(projectType);",
    "  state.kpiProfile = profile;",
    "",
    "  const kpis = Array.isArray(state.kpis)",
    "    ? state.kpis.filter((item) => isPlainObject(item))",
    "    : [];",
    "  const stageChecklist = Array.isArray(state.progressState?.stageChecklist) ? state.progressState.stageChecklist : [];",
    "  const governedSessions = Array.isArray(state.governedSessions) ? state.governedSessions.filter((item) => isPlainObject(item)) : [];",
    "  const requiredArtifactPaths = buildRequiredArtifactPaths(state);",
    "  const presentArtifactCount = requiredArtifactPaths.filter((artifactPath) => fs.existsSync(path.join(workspaceRoot, artifactPath))).length;",
    "  const latestGovernanceChange = latestMtime(requiredArtifactPaths.map((artifactPath) => path.join(workspaceRoot, artifactPath)));",
    '  const now = Date.now();',
    '  const gitTracked = String(state.gitStatus?.trackedByGit || "unknown");',
    '  const gitCommit = String(state.gitStatus?.lastCommit?.sha || "TBD");',
    '  const domainMode = inferDashboardDomainMode(projectType);',
    "  const planReviewComplete = countCompletedStages(stageChecklist, \"plan-\") + countCompletedStages(stageChecklist, \"review-\");",
    "  const totalPlanReviewStages = 6;",
    "  const fullyGovernedSessions = governedSessions.filter(",
    "    (session) => session.governance?.opened === true && Array.isArray(session.outputs) && session.outputs.length > 0",
    "  ).length;",
    "  const traceableSessions = governedSessions.filter(",
    "    (session) => Array.isArray(session.outputs) && session.outputs.length > 0 && isString(session.nextStep) && session.nextStep.length > 0",
    "  ).length;",
    "  const sessionsWithReview = governedSessions.filter(",
    "    (session) => ![\"pending\", \"not-started\"].includes(String(session.verification?.reviewStatus || \"\").toLowerCase())",
    "  ).length;",
    "  const sessionsWithTestEvidence = governedSessions.filter(",
    "    (session) => ![\"pending\", \"not-started\"].includes(String(session.verification?.testsStatus || \"\").toLowerCase())",
    "  ).length;",
    "  const versionCount = Array.isArray(state.versionLedger) ? state.versionLedger.length : 0;",
    "  const timelineCount = Array.isArray(state.timeline) ? state.timeline.length : 0;",
    "  const entityCount = Array.isArray(state.entities) ? state.entities.length : 0;",
    "  const characterCount = Array.isArray(state.entities)",
    "    ? state.entities.filter((entity) => String(entity.type || \"\").toLowerCase() === \"character\").length",
    "    : 0;",
    "  const workstreamCount = Array.isArray(state.progressState?.workstreams) ? state.progressState.workstreams.length : 0;",
    "",
    "  const computed = {",
    '    "governance-freshness": latestGovernanceChange === 0',
    "      ? { value: \"missing-evidence\", status: \"risk\", interpretation: \"Governance artifacts are missing or empty, so freshness cannot be established.\" }",
    "      : now - latestGovernanceChange <= 24 * 60 * 60 * 1000",
    "        ? { value: \"current\", status: \"ok\", interpretation: \"Governance artifacts were refreshed within the last 24 hours.\" }",
    "        : { value: \"stale\", status: \"warning\", interpretation: \"Governance artifacts have not been refreshed recently enough for reliable handover.\" },",
    '    "planning-review-completion": {',
    "      value: String(planReviewComplete) + \" / \" + String(totalPlanReviewStages) + \" gates complete\",",
    "      status: statusFromFraction(planReviewComplete, totalPlanReviewStages),",
    '      interpretation: planReviewComplete >= totalPlanReviewStages',
    '        ? "All required planning and review gates have been completed before implementation."',
    '        : "Continue the plan/review ladder until all six gates are complete and the goal is frozen."',
    "    },",
    '    "contract-coverage": {',
    "      value: String(governedSessions.filter((session) => isString(session.chunkId) && session.chunkId.length > 0 && isString(session.nextStep) && session.nextStep.length > 0).length) + \" / \" + String(governedSessions.length || 1) + \" chunks with contract-ready state\",",
    "      status: statusFromFraction(",
    "        governedSessions.filter((session) => isString(session.chunkId) && session.chunkId.length > 0 && isString(session.nextStep) && session.nextStep.length > 0).length,",
    "        governedSessions.length || 1",
    "      ),",
    '      interpretation: governedSessions.length > 0 && governedSessions.every((session) => isString(session.chunkId) && session.chunkId.length > 0 && isString(session.nextStep) && session.nextStep.length > 0)',
    '        ? "Governed sessions are carrying the minimum contract signals needed for chunk-based execution."',
    '        : "Some sessions still need explicit contract scope, next-step, or chunk identifiers."',
    "    },",
    '    "session-resumability": {',
    "      value: String(presentArtifactCount) + \" / \" + String(requiredArtifactPaths.length) + \" artifacts present\",",
    "      status: statusFromFraction(presentArtifactCount, requiredArtifactPaths.length),",
    '      interpretation: presentArtifactCount >= requiredArtifactPaths.length',
    '        ? "Required artifacts are present, improving restart safety across future sessions."',
    '        : "Some resumability artifacts are missing, which weakens safe continuation."',
    "    },",
    '    "session-governance-coverage": {',
    "      value: String(fullyGovernedSessions) + \" / \" + String(governedSessions.length || 1) + \" sessions governed\",",
    "      status: statusFromFraction(fullyGovernedSessions, governedSessions.length || 1),",
    '      interpretation: fullyGovernedSessions >= Math.max(1, governedSessions.length)',
    '        ? "Every visible session has governance and outputs attached."',
    '        : "Some session records still need governance open/close evidence or outputs."',
    "    },",
    '    "independent-evaluation-discipline": {',
    "      value: String(sessionsWithReview) + \" / \" + String(governedSessions.length || 1) + \" sessions independently reviewed\",",
    "      status: statusFromFraction(sessionsWithReview, governedSessions.length || 1),",
    '      interpretation: sessionsWithReview >= Math.max(1, governedSessions.length)',
    '        ? "Independent review or QA evidence exists for every governed session."',
    '        : "Some sessions still rely on incomplete or missing independent evaluation evidence."',
    "    },",
    '    "evidence-traceability": {',
    "      value: String(traceableSessions) + \" / \" + String(governedSessions.length || 1) + \" sessions traceable\",",
    "      status: statusFromFraction(traceableSessions, governedSessions.length || 1),",
    '      interpretation: traceableSessions >= Math.max(1, governedSessions.length)',
    '        ? "Governed sessions keep evidence and next steps visible."',
    '        : "Some sessions are missing output links or the next step needed for clean handover."',
    "    },",
    '    "git-history-visibility": gitTracked === "yes" && gitCommit !== "TBD"',
    '      ? { value: "tracked", status: "ok", interpretation: "Git history is available for dashboard and governance traces." }',
    '      : { value: "not-tracked", status: "warning", interpretation: "Connect the workspace to Git so stakeholders can audit progress and decisions over time." },',
    '    "ax-dx-adoption": {',
    '      value: governedSessions.length > 0 && requiredArtifactPaths.length > 0 ? "operational" : "partial",',
    '      status: governedSessions.length > 0 ? "ok" : "warning",',
    '      interpretation: governedSessions.length > 0',
    '        ? "The workspace exposes dashboard, governance, and session visibility for DX/AX operating models."',
    '        : "Session-level governance visibility still needs to be populated for real work."',
    "    },",
    '    "test-coverage-discipline": {',
    "      value: String(sessionsWithTestEvidence) + \" sessions with test evidence\",",
    '      status: sessionsWithTestEvidence > 0 ? "ok" : "warning",',
    '      interpretation: sessionsWithTestEvidence > 0',
    '        ? "Programming sessions already carry test evidence or a documented verification result."',
    '        : "No test or verification evidence has been recorded yet for governed delivery sessions."',
    "    },",
    '    "release-traceability": {',
    "      value: String(versionCount) + \" ledger entries\",",
    '      status: versionCount > 0 ? "ok" : "warning",',
    '      interpretation: versionCount > 0',
    '        ? "Version or feature-wave tracking is active in the dashboard."',
    '        : "The version ledger still needs at least one tracked release or draft entry."',
    "    },",
    '    "service-operability-readiness": {',
    "      value: String(workstreamCount) + \" workstreams / \" + String(sessionsWithReview) + \" reviewed sessions\",",
    '      status: sessionsWithReview > 0 ? "ok" : "warning",',
    '      interpretation: sessionsWithReview > 0',
    '        ? "Delivery governance already includes review evidence useful for service operability and release safety."',
    '        : "Runbooks, review evidence, or release readiness records still need to be populated."',
    "    },",
    '    "story-continuity-integrity": {',
    "      value: String(timelineCount) + \" timeline entries / \" + String(entityCount) + \" entities\",",
    '      status: timelineCount > 0 && entityCount > 0 ? "ok" : "warning",',
    '      interpretation: timelineCount > 0 && entityCount > 0',
    '        ? "Narrative continuity can be reviewed from the timeline and entity ledgers."',
    '        : "Story continuity needs timeline and entity tracking to stay reliable across sessions."',
    "    },",
    '    "character-ledger-freshness": {',
    "      value: String(characterCount) + \" character entries\",",
    '      status: characterCount > 0 ? "ok" : "warning",',
    '      interpretation: characterCount > 0',
    '        ? "Character or role entities are visible for session-to-session continuity review."',
    '        : "Important characters or equivalent domain entities still need a visible ledger."',
    "    },",
    '    "evidence-quality": {',
    "      value: String(traceableSessions) + \" traceable sessions\",",
    '      status: traceableSessions > 0 ? "ok" : "warning",',
    '      interpretation: traceableSessions > 0',
    '        ? "Claims and progress can be traced through outputs and next steps."',
    '        : "Evidence trails still need live updates to support reliable review."',
    "    },",
    '    "learning-loop-completion": {',
    "      value: String(timelineCount) + \" modules / \" + String(versionCount) + \" iterations\",",
    '      status: timelineCount > 0 && versionCount > 0 ? "ok" : "warning",',
    '      interpretation: timelineCount > 0 && versionCount > 0',
    '        ? "Learning cycles can be reviewed from module and iteration records."',
    '        : "Learning or research loops still need explicit module and iteration records."',
    "    },",
    '    "initiative-traceability": {',
    "      value: String(timelineCount) + \" milestones / \" + String(governedSessions.length) + \" sessions\",",
    '      status: timelineCount > 0 && governedSessions.length > 0 ? "ok" : "warning",',
    '      interpretation: timelineCount > 0 && governedSessions.length > 0',
    '        ? "Initiatives, milestones, and governed execution records can be reviewed together."',
    '        : "Milestone or initiative traces still need explicit dashboard records."',
    "    },",
    '    "stakeholder-visibility": {',
    '      value: fs.existsSync(path.join(workspaceRoot, "docs", "ai-harness", "dashboard", "index.html")) ? "visible" : "missing",',
    '      status: fs.existsSync(path.join(workspaceRoot, "docs", "ai-harness", "dashboard", "index.html")) ? "ok" : "risk",',
    '      interpretation: "The dashboard remains the main readable control surface for developers and non-developers alike.",',
    "    },",
    "  };",
    "",
    "  for (const definition of requiredDefinitions) {",
    "    const resolved = computed[definition.id] || {",
    "      value: definition.defaultValue,",
    "      status: definition.defaultStatus,",
    "      interpretation: definition.defaultInterpretation,",
    "    };",
    "",
    "    upsertKpi(kpis, {",
    "      id: definition.id,",
    "      label: definition.label,",
    "      target: definition.target,",
    "      value: resolved.value,",
    "      status: resolved.status,",
    "      interpretation: resolved.interpretation,",
    "      perspectives: definition.perspectives,",
    "      required: true,",
    "    });",
    "  }",
    "",
    "  const requiredOrder = new Map(requiredDefinitions.map((definition, index) => [definition.id, index]));",
    "  kpis.sort((left, right) => {",
    "    const leftOrder = requiredOrder.has(left.id) ? requiredOrder.get(left.id) : Number.MAX_SAFE_INTEGER;",
    "    const rightOrder = requiredOrder.has(right.id) ? requiredOrder.get(right.id) : Number.MAX_SAFE_INTEGER;",
    "    return leftOrder - rightOrder;",
    "  });",
    "  state.kpis = kpis;",
    "",
    "  if (domainMode === \"software-delivery\" && sessionsWithTestEvidence === 0) {",
    "    const infoIssue = {",
    '      id: "test-evidence-gap",',
    '      severity: "warning",',
    '      status: "open",',
    '      summary: "Software-delivery sessions should add test evidence or a documented verification gap.",',
    '      owner: "harness-quality-gate",',
    '      firstSeenAt: "auto-refresh",',
    '      lastSeenAt: new Date().toISOString(),',
    "    };",
    "    const issues = Array.isArray(state.errors) ? [...state.errors.filter((issue) => String(issue.id || \"\") !== infoIssue.id)] : [];",
    "    issues.push(infoIssue);",
    "    state.errors = issues;",
    "  }",
    "}",
    "",
    "function refreshExecutiveSummary(state) {",
    "  const stageChecklist = Array.isArray(state.progressState?.stageChecklist) ? state.progressState.stageChecklist : [];",
    "  const overallProgressPercent = stageProgressPercent(stageChecklist);",
    "  const currentStage = deriveCurrentStage(stageChecklist);",
    "  const blocked = Boolean(state.progressState?.blocked);",
    "  const openErrors = Array.isArray(state.errors)",
    "    ? state.errors.filter((item) => String(item.status || \"\").toLowerCase() === \"open\")",
    "    : [];",
    "",
    "  state.executiveSummary = {",
    "    ...state.executiveSummary,",
    "    overallProgressPercent,",
    "    currentStage,",
    "    overallStatus: blocked",
    '      ? "blocked"',
    '      : openErrors.some((item) => String(item.severity || "").toLowerCase() === "critical")',
    '        ? "at-risk"',
    '        : "active",',
    '    lastUpdated: new Date().toISOString(),',
    "  };",
    "}",
    "",
    "function refreshState(state, workspaceRoot) {",
    "  refreshArtifactStatuses(state, workspaceRoot);",
    "  state.gitStatus = collectGitStatus(workspaceRoot);",
    "  refreshGovernanceState(state);",
    "  refreshSessionLog(state);",
    "  refreshGovernedSessions(state);",
    "  refreshGovernanceKpis(state, workspaceRoot);",
    "  refreshExecutiveSummary(state);",
    "  state.meta = {",
    "    ...state.meta,",
    '    lastAutoRefreshAt: new Date().toISOString(),',
    "  };",
    "  return state;",
    "}",
    "",
    "function ensureValidState(state) {",
    "  const validation = validateDashboardStateShape(state);",
    "  if (!validation.valid) {",
    '    throw new Error("Dashboard state validation failed:\\n" + validation.errors.map((error) => "  - " + error).join("\\n"));',
    "  }",
    "}",
    "",
    "function createStandaloneSnapshotHtml(indexHtml, css, js, state) {",
    '  const stateJson = JSON.stringify(state, null, 2).replace(/</g, "\\\\u003c");',
    "",
    "  let html = indexHtml.replace(",
    '    /<link rel="stylesheet" href="\\.\\/app\\.css" \\/>/,',
    '    "<style>\\n" + css + "\\n</style>"',
    "  );",
    "  html = html.replace(",
    '    /<script src="\\.\\/app\\.js"><\\/script>/,',
    '    "<script>\\n" + js + "\\n</script>"',
    "  );",
    "  html = html.replace(",
    '    /<script id="dashboard-bootstrap-data" type="application\\/json">[\\s\\S]*?<\\/script>/,',
    '    \'<script id="dashboard-bootstrap-data" type="application/json">\' + stateJson + "</script>"',
    "  );",
    "  return html;",
    "}",
    "",
    "function handleRefresh() {",
    "  const workspaceRoot = getWorkspaceRoot();",
    "  const statePath = getStatePath();",
    '  const patchPath = getOption("--patch", "");',
    "  let state = readJsonFile(statePath);",
    "",
    "  if (patchPath) {",
    "    const patch = readJsonFile(path.resolve(patchPath));",
    "    state = deepMerge(state, patch);",
    "  }",
    "",
    "  state = refreshState(state, workspaceRoot);",
    "  ensureValidState(state);",
    "  state.governanceState = {",
    "    ...state.governanceState,",
    '    dashboardSyncStatus: "current",',
    "  };",
    "  writeJsonFile(statePath, state);",
    "",
    "  const outputLines = [",
    '    "Dashboard state refreshed.",',
    '    "  - state: " + safeRelativePath(workspaceRoot, statePath),',
    '    "  - current stage: " + String(state.executiveSummary?.currentStage || "unknown"),',
    '    "  - overall progress: " + String(state.executiveSummary?.overallProgressPercent ?? 0) + "%",',
    '    "  - git tracked: " + String(state.gitStatus?.trackedByGit || "unknown"),',
    '    "  - branch: " + String(state.gitStatus?.currentBranch || "TBD"),',
    '    "  - governed sessions: " + String(Array.isArray(state.governedSessions) ? state.governedSessions.length : 0),',
    '    "  - required KPI profile: " + String(state.kpiProfile?.id || "unknown"),',
    "  ];",
    "",
    '  console.log(outputLines.join("\\n"));',
    "}",
    "",
    "function handleValidate() {",
    "  const statePath = getStatePath();",
    "  const state = readJsonFile(statePath);",
    "  const validation = validateDashboardStateShape(state);",
    "",
    "  if (!validation.valid) {",
    '    console.error("Dashboard state is invalid:");',
    "    for (const error of validation.errors) {",
    '      console.error("  - " + error);',
    "    }",
    "    process.exit(1);",
    "  }",
    "",
    '  console.log("Dashboard state is valid.");',
    '  console.log("  - state: " + statePath);',
    '  console.log("  - KPI profile: " + String(state.kpiProfile?.id || "unknown"));',
    '  console.log("  - governed sessions: " + String(Array.isArray(state.governedSessions) ? state.governedSessions.length : 0));',
    "}",
    "",
    "function serveFile(requestPath, rootDir, response) {",
    '  const normalized = requestPath === "/" ? "/index.html" : requestPath;',
    "  const targetPath = path.normalize(path.join(rootDir, normalized));",
    "",
    "  if (!targetPath.startsWith(rootDir)) {",
    '    response.writeHead(403, { "content-type": "text/plain; charset=utf-8" });',
    '    response.end("Forbidden");',
    "    return;",
    "  }",
    "",
    "  if (!fs.existsSync(targetPath) || fs.statSync(targetPath).isDirectory()) {",
    '    response.writeHead(404, { "content-type": "text/plain; charset=utf-8" });',
    '    response.end("Not found");',
    "    return;",
    "  }",
    "",
    "  const ext = path.extname(targetPath).toLowerCase();",
    "  const contentTypeMap = {",
    '    ".html": "text/html; charset=utf-8",',
    '    ".css": "text/css; charset=utf-8",',
    '    ".js": "text/javascript; charset=utf-8",',
    '    ".json": "application/json; charset=utf-8",',
    '    ".md": "text/markdown; charset=utf-8",',
    "  };",
    '  const contentType = contentTypeMap[ext] || "application/octet-stream";',
    '  response.writeHead(200, { "content-type": contentType });',
    "  fs.createReadStream(targetPath).pipe(response);",
    "}",
    "",
    "function handleServe() {",
    '  const port = Number(getOption("--port", "43110"));',
    '  const host = getOption("--host", "127.0.0.1");',
    "",
    "  const server = http.createServer((request, response) => {",
    '    const url = new URL(request.url || "/", "http://localhost");',
    "    serveFile(url.pathname, dashboardDir, response);",
    "  });",
    "",
    "  server.listen(port, host, () => {",
    '    console.log(`Dashboard server running at http://${host}:${port}`);',
    '    console.log("Press Ctrl+C to stop.");',
    "  });",
    "}",
    "",
    "function handleExportStatic() {",
    "  const workspaceRoot = getWorkspaceRoot();",
    '  const outputDir = path.resolve(getOption("--out", path.join(dashboardDir, "exports", "latest")));',
    "  const statePath = getStatePath();",
    '  const indexPath = path.join(dashboardDir, "index.html");',
    '  const cssPath = path.join(dashboardDir, "app.css");',
    '  const jsPath = path.join(dashboardDir, "app.js");',
    "",
    "  const state = refreshState(readJsonFile(statePath), workspaceRoot);",
    "  ensureValidState(state);",
    "  state.governanceState = {",
    "    ...state.governanceState,",
    '    dashboardSyncStatus: "current",',
    "  };",
    "",
    "  fs.mkdirSync(outputDir, { recursive: true });",
    '  fs.mkdirSync(path.join(outputDir, "state"), { recursive: true });',
    "",
    '  const indexHtml = fs.readFileSync(indexPath, "utf-8");',
    '  const css = fs.readFileSync(cssPath, "utf-8");',
    '  const js = fs.readFileSync(jsPath, "utf-8");',
    '  const schema = fs.readFileSync(defaultSchemaPath, "utf-8");',
    "",
    '  fs.writeFileSync(path.join(outputDir, "index.html"), indexHtml, "utf-8");',
    '  fs.writeFileSync(path.join(outputDir, "app.css"), css, "utf-8");',
    '  fs.writeFileSync(path.join(outputDir, "app.js"), js, "utf-8");',
    '  fs.writeFileSync(path.join(outputDir, "state", "dashboard-state.json"), JSON.stringify(state, null, 2) + "\\n", "utf-8");',
    '  fs.writeFileSync(path.join(outputDir, "state", "dashboard-state.schema.json"), schema, "utf-8");',
    "  fs.writeFileSync(",
    '    path.join(outputDir, "snapshot.html"),',
    "    createStandaloneSnapshotHtml(indexHtml, css, js, state),",
    '    "utf-8"',
    "  );",
    "",
    '  console.log("Static dashboard export complete.");',
    '  console.log("  - output: " + safeRelativePath(workspaceRoot, outputDir));',
    '  console.log("  - shareable snapshot: " + safeRelativePath(workspaceRoot, path.join(outputDir, "snapshot.html")));',
    "}",
    "",
    "function printHelp() {",
    '  console.log("Dashboard Operations");',
    '  console.log("");',
    '  console.log("Commands:");',
    '  console.log("  refresh [--patch path] [--state path] [--workspace-root path]");',
    '  console.log("  validate [--state path]");',
    '  console.log("  serve [--port 43110] [--host 127.0.0.1]");',
    '  console.log("  export-static [--out path] [--state path] [--workspace-root path]");',
    "}",
    "",
    "switch (command) {",
    '  case "refresh":',
    "    handleRefresh();",
    "    break;",
    '  case "validate":',
    "    handleValidate();",
    "    break;",
    '  case "serve":',
    "    handleServe();",
    "    break;",
    '  case "export-static":',
    "    handleExportStatic();",
    "    break;",
    "  default:",
    "    printHelp();",
    "    break;",
    "}",
    "",
  ].join("\n");
}

export function generateDashboardOperationFiles(
  params: WorkspaceInitParams
): GeneratedFile[] {
  if (params.includeHarnessEngineering === false) {
    return [];
  }

  return [
    {
      relativePath: "docs/ai-harness/dashboard/scripts/README.md",
      content: buildDashboardOpsReadme(),
    },
    {
      relativePath: "docs/ai-harness/dashboard/scripts/dashboard-ops.mjs",
      content: buildDashboardOpsScript(),
    },
  ];
}
